// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: test.proto

package proto.test;

public interface TestReplyOrBuilder extends
    // @@protoc_insertion_point(interface_extends:TestReply)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string name = 1;</code>
   */
  java.util.List<java.lang.String>
      getNameList();
  /**
   * <code>repeated string name = 1;</code>
   */
  int getNameCount();
  /**
   * <code>repeated string name = 1;</code>
   */
  java.lang.String getName(int index);
  /**
   * <code>repeated string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes(int index);
}
